.\"
.\" Copyright (c) 2008 GeNUA mbH <info@genua.de>
.\" Copyright (c) 2003 Robert Watson <rwatson@FreeBSD.org>
.\" Copyright (c) 2001 Dima Dorfman <dima@unixfreak.org>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" $FreeBSD: extattr_get_file.2,v 1.19 2008/01/29 18:15:38 trhodes Exp $
.\"
.Dd January 29, 2008
.Dt EXTATTR 2
.Os
.Sh NAME
.Nm extattr_get_fd ,
.Nm extattr_set_fd ,
.Nm extattr_delete_fd ,
.Nm extattr_list_fd ,
.Nm extattr_get_file ,
.Nm extattr_set_file ,
.Nm extattr_delete_file ,
.Nm extattr_list_file ,
.Nm extattr_get_link ,
.Nm extattr_set_link ,
.Nm extattr_delete_link ,
.Nm extattr_list_link
.Nd system calls to manipulate extended attributes
.Sh SYNOPSIS
.In sys/types.h
.In sys/extattr.h
.Ft ssize_t
.Fn extattr_get_fd "int fd" "int attrnamespace" "const char *attrname" "void *data" "size_t nbytes"
.Ft int
.Fn extattr_set_fd "int fd" "int attrnamespace" "const char *attrname" "const void *data" "size_t nbytes"
.Ft int
.Fn extattr_delete_fd "int fd" "int attrnamespace" "const char *attrname"
.Ft ssize_t
.Fn extattr_list_fd "int fd" "int attrnamespace" "void *data" "size_t nbytes"
.Ft ssize_t
.Fn extattr_get_file "const char *path" "int attrnamespace" "const char *attrname" "void *data" "size_t nbytes"
.Ft int
.Fn extattr_set_file "const char *path" "int attrnamespace" "const char *attrname" "const void *data" "size_t nbytes"
.Ft int
.Fn extattr_delete_file "const char *path" "int attrnamespace" "const char *attrname"
.Ft ssize_t
.Fn extattr_list_file "const char *path" "int attrnamespace" "void *data" "size_t nbytes"
.Ft ssize_t
.Fn extattr_get_link "const char *path" "int attrnamespace" "const char *attrname" "void *data" "size_t nbytes"
.Ft int
.Fn extattr_set_link "const char *path" "int attrnamespace" "const char *attrname" "const void *data" "size_t nbytes"
.Ft int
.Fn extattr_delete_link "const char *path" "int attrnamespace" "const char *attrname"
.Ft ssize_t
.Fn extattr_list_link "const char *path" "int attrnamespace" "void *data" "size_t nbytes"
.Sh DESCRIPTION
Extended attributes are userland-manipulable metadata associated with file
system objects.
They exist as
.Qq Li name, value
pairs within a set of namespaces.
.Pp
The
.Fn extattr_get_file
system call retrieves the value of the specified extended attribute into
a buffer of
.Fa nbytes
bytes pointed to by
.Fa data .
.Pp
The
.Fn extattr_set_file
system call sets the value of the specified extended attribute to the data
contained in
.Fa data .
.Pp
The
.Fn extattr_delete_file
system call deletes the specified extended attribute.
.Pp
The
.Fn extattr_list_file
returns a list of attributes present in the requested namespace.
Each entry consists of a single byte containing the length
of the attribute name, followed by the attribute name.
Note that the attribute name is not terminated by ASCII 0 (nul).
.Pp
The
.Fn extattr_get_file ,
and
.Fn extattr_list_file
calls consume the
.Fa data
and
.Fa nbytes
arguments in the same way as
.Xr read 2 ,
while
.Fn extattr_set_file
consumes these arguments in the same way as
.Xr write 2 .
.Pp
If
.Fa data
is
.Dv NULL
in a call to
.Fn extattr_get_file
and
.Fn extattr_list_file
then the size of defined extended attribute data will be returned, rather
than the quantity read, permitting applications to test the size of the
data without performing a read.
The
.Fn extattr_delete_link ,
.Fn extattr_get_link ,
and
.Fn extattr_set_link
system calls behave in the same way as their _file counterparts, except that
they do not follow symlinks.
.Pp
The
.Fn extattr_get_fd ,
.Fn extattr_set_fd ,
.Fn extattr_delete_fd ,
and
.Fn extattr_list_fd ,
calls are identical to their
.Qq Li _file
counterparts except for the first argument.
The
.Qq Li _fd
functions take a file descriptor, while the
.Qq Li _file
functions take a path.
Both arguments describe a file system object associated with the extended
attribute that should be manipulated.
.Pp
The following arguments are common to all the system calls described in this
document:
.Bl -tag -width attrnamespace
.It Fa attrnamespace
the namespace in which the extended attribute resides. See
.Xr extattr 9
and
.Xr extattr_namespace_to_string 2 .
.It Fa attrname
the name of the extended attribute
.El
.Pp
Named extended attribute semantics vary according to the underlying file
system.
Not all operations may be supported for a particular attribute.
Additionally, the format of the data in
.Fa data
can be attribute-specific.
.Sh RETURN VALUES
If successful, the
.Fn extattr_get_file ,
.Fn extattr_set_file ,
and
.Fn extattr_list_file
calls return the number of bytes
that were read from or written to
.Fa data ,
respectively, or if
.Fa data
was
.Dv NULL ,
then
.Fn extattr_get_file
and
.Fn extattr_list_file
return the number of bytes available to read.
If any of the calls are unsuccessful, \-1 is returned
and the global variable
.Va errno
is set to indicate the error.
.Pp
.Rv -std extattr_delete_file
.Sh ERRORS
Errors emerging from file system specific routines are not restricted to any
particular subset, and can be anything. The errors returned by FFS2 are:
.Bl -tag -width Er
.It Bq Er EIO
An I/O error occurred while reading from or writing to the file system.
.It Bq EINVAL
Attribute name and content must be at least one byte long.
.It Bq EINVAL
Corrupted extended attribute entry.
.It Bq Er ENOMEM
Could not allocate memory to describe inode's extended attribute area.
.It Bq ENOSPC
The file system is out of space.
.It Bq Er EOPNOTSUPP
The file system object being referenced is not a file, a directory or a
symbolic link.
.It Bq Er EPERM
Insufficient credentials. See
.Xr extattr 9
for details.
.It Bq Er EROFS
Write operation attempted on read-only file system.
.El
.Pp
There is also a subset of errors returned directly by the system calls, and
these include:
.Bl -tag -width Er
.It Bq Er EFAULT
The
.Fa attrnamespace
and
.Fa attrname
arguments,
or the memory range defined by
.Fa data
and
.Fa nbytes
point outside the process's allocated address space.
.It Bq Er ENAMETOOLONG
The attribute name was longer than
.Dv EXTATTR_MAXNAMELEN .
.El
.Pp
The
.Fn extattr_get_fd ,
.Fn extattr_set_fd ,
.Fn extattr_delete_fd ,
and
.Fn extattr_list_fd
system calls may also fail with:
.Bl -tag -width Er
.It Bq Er EBADF
The file descriptor referenced by
.Fa fd
was invalid.
.El
.Pp
Additionally, the
.Fn extattr_get_file ,
.Fn extattr_set_file ,
and
.Fn extattr_delete_file
calls may also fail due to the following errors:
.Bl -tag -width Er
.It Bq Er ENOATTR
The requested attribute was not defined for this file.
.It Bq Er ENOTDIR
A component of the path prefix is not a directory.
.It Bq Er ENAMETOOLONG
A component of a pathname exceeded 255 characters,
or an entire path name exceeded 1023 characters.
.It Bq Er ENOENT
A component of the path name that must exist does not exist.
.It Bq Er EACCES
Search permission is denied for a component of the path prefix.
.El
.Sh SEE ALSO
.Xr extattr 3 ,
.Xr getextattr 8 ,
.Xr setextattr 8 ,
.Xr extattr 9
