.\"
.\" Copyright (c) 2008 GeNUA mbH <info@genua.de>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd February 5, 2008
.Dt EXTATTR 3
.Os
.Sh NAME
.Nm extattr_namespace_to_string ,
.Nm extattr_string_to_namespace
.Nd convert between numeric and alphabetical representations of an extended
attribute namespace
.Sh SYNOPSIS
.In sys/extattr.h
.Ft int
.Fn extattr_namespace_to_string "int attrnamespace" "char **string"
.Ft int
.Fn extattr_string_to_namespace "const char *string" "int *attrnamespace"
.Sh DESCRIPTION
The
.Fn extattr_namespace_to_string
function maps the
.Fa attrnamespace
integer containing an extended attribute namespace identifier code to a
corresponding alphabetical representation in
.Fa string .
Memory for
.Fa string
is allocated dynamically, and it is up to the caller to release it using
.Xr free 3
when appropriate.
.Pp
The
.Fn extattr_string_to_namespace
function maps the
.Fa string
containing the alphabetical representation of an extended attribute
namespace identifier to a corresponding numeric code in
.Fa attrnamespace .
.Sh RETURN VALUES
If the call succeeds, 0 is returned.
Otherwise, \-1 is returned and
.Va errno
is set to indicate the error.
.Sh ERRORS
.Bl -tag -width Er
.It Bq Er EINVAL
The requested namespace could not be identified.
.El
.Sh SEE ALSO
.Xr extattr 2 ,
.Xr getextattr 8 ,
.Xr setextattr 8 ,
.Xr extattr 9
.Sh CAVEATS
Currently, only the
.Dv EXTATTR_NAMESPACE_USER
.Pq Dq user
and
.Dv EXTATTR_NAMESPACE_SYSTEM
.Pq Dq system
namespaces are supported.
